services:
  - type: web
    name: apitygia
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
