services:
  - type: web
    name: apitygia
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: uvicorn apitygia:app --host 0.0.0.0 --port $PORT
