services:
  - type: web
    name: apitygia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "playwright install chromium && uvicorn api:app --host 0.0.0.0 --port 8000"
    region: singapore
    plan: free

