services:
  - type: web
    name: apitygia
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m playwright install --with-deps
    startCommand: uvicorn api:app --host 0.0.0.0 --port 8001
